import { NextResponse } from 'next/server';

const INDUSTRY_PROFILES: Record<string, any> = {
  // Food Service
  '722511': {
    naics_code: '722511',
    title: 'Full-Service Restaurants',
    description: 'Establishments primarily engaged in providing food services to patrons who order and are served while seated.',
    employee_count_range: '20-99',
    annual_revenue_range: '$1M-$5M',
    growth_rate: 3.2,
    risk_level: 'medium',
    key_metrics: {
      avg_gross_margin: 62.0,
      avg_operating_margin: 8.5,
      avg_dso: 7,
      avg_current_ratio: 1.2,
      avg_debt_to_equity: 1.8,
      avg_inventory_turnover: 12.0,
    },
  },
  '722513': {
    naics_code: '722513',
    title: 'Limited-Service Restaurants',
    description: 'Fast food and quick-service establishments where patrons order and pay before eating.',
    employee_count_range: '10-49',
    annual_revenue_range: '$500K-$2M',
    growth_rate: 4.1,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 58.0,
      avg_operating_margin: 12.0,
      avg_dso: 5,
      avg_current_ratio: 1.4,
      avg_debt_to_equity: 1.2,
      avg_inventory_turnover: 18.0,
    },
  },
  // Construction
  '236220': {
    naics_code: '236220',
    title: 'Commercial Building Construction',
    description: 'Construction of commercial, industrial, and institutional buildings.',
    employee_count_range: '50-249',
    annual_revenue_range: '$5M-$25M',
    growth_rate: 5.8,
    risk_level: 'high',
    key_metrics: {
      avg_gross_margin: 22.0,
      avg_operating_margin: 6.5,
      avg_dso: 45,
      avg_current_ratio: 1.35,
      avg_debt_to_equity: 2.1,
      avg_inventory_turnover: 6.0,
    },
  },
  '238220': {
    naics_code: '238220',
    title: 'Plumbing, Heating & Air-Conditioning Contractors',
    description: 'Installation and repair of plumbing, heating, and air-conditioning systems.',
    employee_count_range: '10-99',
    annual_revenue_range: '$1M-$10M',
    growth_rate: 4.5,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 35.0,
      avg_operating_margin: 10.0,
      avg_dso: 30,
      avg_current_ratio: 1.6,
      avg_debt_to_equity: 1.3,
      avg_inventory_turnover: 8.0,
    },
  },
  // Manufacturing
  '333998': {
    naics_code: '333998',
    title: 'All Other Miscellaneous General Purpose Machinery Manufacturing',
    description: 'Manufacture of general purpose machinery and equipment.',
    employee_count_range: '50-249',
    annual_revenue_range: '$10M-$50M',
    growth_rate: 3.8,
    risk_level: 'medium',
    key_metrics: {
      avg_gross_margin: 32.0,
      avg_operating_margin: 9.5,
      avg_dso: 38,
      avg_current_ratio: 1.5,
      avg_debt_to_equity: 1.6,
      avg_inventory_turnover: 5.5,
    },
  },
  '339950': {
    naics_code: '339950',
    title: 'Sign Manufacturing',
    description: 'Manufacturing of signs and advertising displays.',
    employee_count_range: '10-99',
    annual_revenue_range: '$1M-$10M',
    growth_rate: 3.5,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 45.0,
      avg_operating_margin: 12.0,
      avg_dso: 28,
      avg_current_ratio: 1.7,
      avg_debt_to_equity: 1.1,
      avg_inventory_turnover: 7.0,
    },
  },
  // Retail
  '445110': {
    naics_code: '445110',
    title: 'Supermarkets and Other Grocery Stores',
    description: 'Retailers primarily engaged in retailing a general line of food products.',
    employee_count_range: '50-249',
    annual_revenue_range: '$5M-$50M',
    growth_rate: 2.1,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 28.0,
      avg_operating_margin: 3.5,
      avg_dso: 5,
      avg_current_ratio: 1.1,
      avg_debt_to_equity: 1.9,
      avg_inventory_turnover: 14.0,
    },
  },
  '453910': {
    naics_code: '453910',
    title: 'Pet and Pet Supplies Stores',
    description: 'Retailers selling pets, pet food, and pet supplies.',
    employee_count_range: '5-49',
    annual_revenue_range: '$500K-$5M',
    growth_rate: 6.2,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 42.0,
      avg_operating_margin: 8.0,
      avg_dso: 12,
      avg_current_ratio: 1.8,
      avg_debt_to_equity: 1.0,
      avg_inventory_turnover: 6.0,
    },
  },
  // Professional Services
  '541211': {
    naics_code: '541211',
    title: 'Offices of Certified Public Accountants',
    description: 'Establishments of accountants and auditors providing accounting, bookkeeping, and related services.',
    employee_count_range: '5-49',
    annual_revenue_range: '$500K-$5M',
    growth_rate: 3.0,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 55.0,
      avg_operating_margin: 22.0,
      avg_dso: 35,
      avg_current_ratio: 2.0,
      avg_debt_to_equity: 0.8,
      avg_inventory_turnover: 0,
    },
  },
  '541512': {
    naics_code: '541512',
    title: 'Computer Systems Design Services',
    description: 'Planning and designing computer systems that integrate hardware, software, and communication technologies.',
    employee_count_range: '20-249',
    annual_revenue_range: '$2M-$25M',
    growth_rate: 7.5,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 38.0,
      avg_operating_margin: 15.0,
      avg_dso: 42,
      avg_current_ratio: 1.9,
      avg_debt_to_equity: 0.9,
      avg_inventory_turnover: 0,
    },
  },
  '541611': {
    naics_code: '541611',
    title: 'Administrative Management and General Management Consulting Services',
    description: 'Providing advice and assistance on management and operational issues.',
    employee_count_range: '10-99',
    annual_revenue_range: '$1M-$10M',
    growth_rate: 5.2,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 48.0,
      avg_operating_margin: 18.0,
      avg_dso: 38,
      avg_current_ratio: 1.8,
      avg_debt_to_equity: 0.7,
      avg_inventory_turnover: 0,
    },
  },
  // Healthcare
  '621111': {
    naics_code: '621111',
    title: 'Offices of Physicians',
    description: 'Establishments of physicians providing medical care to outpatients.',
    employee_count_range: '20-99',
    annual_revenue_range: '$2M-$10M',
    growth_rate: 2.8,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 52.0,
      avg_operating_margin: 14.0,
      avg_dso: 28,
      avg_current_ratio: 1.6,
      avg_debt_to_equity: 1.1,
      avg_inventory_turnover: 4.0,
    },
  },
  '621210': {
    naics_code: '621210',
    title: 'Offices of Dentists',
    description: 'Establishments of dentists providing dental care services.',
    employee_count_range: '5-49',
    annual_revenue_range: '$500K-$3M',
    growth_rate: 3.5,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 58.0,
      avg_operating_margin: 20.0,
      avg_dso: 18,
      avg_current_ratio: 1.9,
      avg_debt_to_equity: 0.9,
      avg_inventory_turnover: 3.0,
    },
  },
  // Transportation
  '484110': {
    naics_code: '484110',
    title: 'General Freight Trucking, Local',
    description: 'Local general freight trucking services.',
    employee_count_range: '10-99',
    annual_revenue_range: '$1M-$10M',
    growth_rate: 3.8,
    risk_level: 'medium',
    key_metrics: {
      avg_gross_margin: 30.0,
      avg_operating_margin: 7.0,
      avg_dso: 25,
      avg_current_ratio: 1.3,
      avg_debt_to_equity: 1.7,
      avg_inventory_turnover: 0,
    },
  },
  // Real Estate
  '531210': {
    naics_code: '531210',
    title: 'Offices of Real Estate Agents and Brokers',
    description: 'Buying, selling, renting, and managing real estate properties.',
    employee_count_range: '5-49',
    annual_revenue_range: '$500K-$5M',
    growth_rate: 4.2,
    risk_level: 'medium',
    key_metrics: {
      avg_gross_margin: 85.0,
      avg_operating_margin: 18.0,
      avg_dso: 15,
      avg_current_ratio: 2.2,
      avg_debt_to_equity: 0.5,
      avg_inventory_turnover: 0,
    },
  },
  // Education
  '611420': {
    naics_code: '611420',
    title: 'Computer Training',
    description: 'Providing instruction in computer programming, software, and systems.',
    employee_count_range: '5-49',
    annual_revenue_range: '$250K-$2M',
    growth_rate: 4.0,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 60.0,
      avg_operating_margin: 16.0,
      avg_dso: 20,
      avg_current_ratio: 1.8,
      avg_debt_to_equity: 0.6,
      avg_inventory_turnover: 0,
    },
  },
  // Automotive
  '811111': {
    naics_code: '811111',
    title: 'General Automotive Repair',
    description: 'General automotive repair and maintenance services.',
    employee_count_range: '5-49',
    annual_revenue_range: '$500K-$3M',
    growth_rate: 2.5,
    risk_level: 'low',
    key_metrics: {
      avg_gross_margin: 48.0,
      avg_operating_margin: 11.0,
      avg_dso: 22,
      avg_current_ratio: 1.5,
      avg_debt_to_equity: 1.2,
      avg_inventory_turnover: 6.0,
    },
  },
  // Wholesale
  '423830': {
    naics_code: '423830',
    title: 'Industrial Machinery and Equipment Merchant Wholesalers',
    description: 'Wholesaling industrial machinery and equipment.',
    employee_count_range: '20-99',
    annual_revenue_range: '$5M-$25M',
    growth_rate: 3.5,
    risk_level: 'medium',
    key_metrics: {
      avg_gross_margin: 25.0,
      avg_operating_margin: 6.0,
      avg_dso: 35,
      avg_current_ratio: 1.4,
      avg_debt_to_equity: 1.5,
      avg_inventory_turnover: 4.5,
    },
  },
  // Entertainment
  '713910': {
    naics_code: '713910',
    title: 'Golf Courses and Country Clubs',
    description: 'Operating golf courses and country clubs.',
    employee_count_range: '50-249',
    annual_revenue_range: '$2M-$10M',
    growth_rate: 2.0,
    risk_level: 'medium',
    key_metrics: {
      avg_gross_margin: 55.0,
      avg_operating_margin: 8.0,
      avg_dso: 10,
      avg_current_ratio: 1.3,
      avg_debt_to_equity: 1.4,
      avg_inventory_turnover: 3.0,
    },
  },
  // Agriculture
  '115210': {
    naics_code: '115210',
    title: 'Support Activities for Animal Production',
    description: 'Providing support services for animal production.',
    employee_count_range: '10-99',
    annual_revenue_range: '$1M-$5M',
    growth_rate: 3.0,
    risk_level: 'medium',
    key_metrics: {
      avg_gross_margin: 35.0,
      avg_operating_margin: 9.0,
      avg_dso: 30,
      avg_current_ratio: 1.4,
      avg_debt_to_equity: 1.3,
      avg_inventory_turnover: 5.0,
    },
  },
};

export async function GET(
  request: Request,
  { params }: { params: { naics: string } }
) {
  const { naics } = params;
  const url = new URL(request.url);
  const zipCode = url.searchParams.get('zip_code') || '00000';

  const profile = INDUSTRY_PROFILES[naics] || {
    naics_code: naics,
    title: 'Industry Profile',
    description: 'Detailed industry analysis and benchmarking data.',
    employee_count_range: '10-99',
    annual_revenue_range: '$1M-$10M',
    growth_rate: 3.5,
    risk_level: 'medium',
    key_metrics: {
      avg_gross_margin: 40.0,
      avg_operating_margin: 10.0,
      avg_dso: 30,
      avg_current_ratio: 1.5,
      avg_debt_to_equity: 1.3,
      avg_inventory_turnover: 6.0,
    },
  };

  return NextResponse.json({
    ...profile,
    zip_code: zipCode,
    local_market_data: {
      median_household_income: 65000 + Math.floor(Math.random() * 40000),
      population_density: zipCode.startsWith('9') ? 'urban' : zipCode.startsWith('1') ? 'urban' : 'suburban',
      competition_level: Math.random() > 0.5 ? 'high' : 'medium',
      business_count: 150 + Math.floor(Math.random() * 850),
    },
  });
}